# clem-ai/docker-compose.yml

version: '3.8'
services:
  db:
    image: postgres:15
    container_name: clem-ai-db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: clem_ai_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: