# clem-ai/docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15
    container_name: clem-ai-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clem_ai
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256 # <-- ADD THIS LINE
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: